spring:
  application:
    name: db-spring-boot-starter
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    base:
      packages: com.zipe
