spring:
  application:
    name: login-spring-boot-starter
  main:
    allow-bean-definition-overriding: true

security:
  enable: true
  verification-type: basic
  record-log-enable: false
  allow-uris: /resources/**,/static/**
  login-uri: /login
  login-success-uri: /dashboard
  login-failure-uri: /login
