spring:
  application:
    name: base-spring-boot-starter
  main:
    allow-bean-definition-overriding: true

mail:
  debug-enable: true
  username: zipe
  pa55word: zipe
  enable-encrypt: false
  host: 127.0.0.1
  port: 25
  smtp-auth-enable: true
  sender: zipe@localhost.com
  transport-protocol: smtp
  smtp-start-tls-enable: true
