spring:
  application:
    name: logon-spring-boot-starter
  main:
    allow-bean-definition-overriding: true

security:
  enable: true
  verification-type: basic #basic 內建基本驗證，ldap LDAP驗證，custom 自訂驗證(需定義 custom-bean-name)
  custom-bean-name:
  record-log-enable: false
  custom-record-log-bean:
  allow-uris: /resources/**,/static/**
  login-uri: /login
  login-success-uri: /dashboard
  login-failure-uri: /login
  csrf-enabled: true
  ldap:
    ip: 127.0.0.1
    domain: ldap.zipe.com
    port: 389
    dn: DC=zipe,DC=local
