# Spring
spring:
  application:
    # 應用名稱
    name: web-service-spring-boot-starter

web:
  service:
    uri-mapping: /webservice/*
    map:
      example:
        beanName: userServiceImpl
        uri-mapping: /user
#      demo:
#        beanName: demoServiceImpl
#        uri-mapping: /demo
